config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :goals
  resource :session, only: [:new, :create, :destroy]
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :title, :description, :visibility, :status, :user_id, presence: true

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token!

  attr_reader :password

  has_many :goals,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: 'Goal'

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save
    self.session_token
  end

  private

  def ensure_session_token!
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?, :log_in!, :log_out!

  def log_in!(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def log_out!
    if signed_in?
      current_user.reset_session_token!
      session[:session_token] = nil
    else
      return nil
    end
  end

  def require_logged_in!
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_logged_in!
  before_action :ensure_visitor_is_goal_creator, only: [:edit, :update, :delete]

  def index
      @others_public_goals = Goal.all.where("user_id != #{current_user.id} AND visibility = 'Public'")
  end

  def new
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to goals_url
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    flash[:notice] = ["Goal successfully deleted!"]
    redirect_to goals_url
  end

  def ensure_visitor_is_goal_creator
    @goal = Goal.find(params[:id])
    if @goal.user_id != current_user.id
      redirect_to goal_url(@goal)
    end
  end

  private

  def goal_params
    params.require(:goal).permit(:title, :description, :visibility, :due_date, :status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      log_in!(@user)
      redirect_to goals_url
    else
      flash[:errors] = ["Invalid Login Credentials"]
      redirect_to new_session_url
    end
  end

  def destroy
    log_out!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in!(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end

  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<H1>Goal Edit Page</H1>

<form action="<%= goal_url(@goal) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Title
    <input type="text" name="goal[title]" value="<%= @goal.title %>">
  </label>
  <BR>
  <label>
    Description<BR>
    <textarea name="goal[description]" rows="8" cols="40"><%= @goal.description %></textarea>
  </label>
  <BR>
  <label>
    Visibility<BR>
    <label>
      Private
      <input type="radio" name="goal[visibility]" value="Private" <%= "checked" if @goal.visibility == 'Private'%> >
    </label>
    <label>
      Public
      <input type="radio" name="goal[visibility]" value="Public" <%= "checked" if @goal.visibility == 'Public' %>>
    </label>
  </label>
  <BR>
  <label>
    Due Date
    <input type="date" name="goal[due_date]" value=<%= @goal.due_date %>>
  </label>
  <BR>
  <label>
    Status
    <select name="goal[status]">
      <option value="not_started" <%= "selected" if @goal.status == 'not_started' %>>Not Started</option>
      <option value="in_progress" <%= "selected" if @goal.status == 'in_progress' %>>In Progress</option>
      <option value="completed" <%= "selected" if @goal.status == 'completed' %>>Completed</option>
    </select>
  </label>
  <BR>
  <input type="submit" value="Update Goal">
</form>

app/views/goals/index.html.erb
<H1>Goals</H1>

Your Goals:<BR>
<% current_user.goals.each do |goal| %>
  <%= link_to goal.title, goal_url(goal.id) %>
  <br>
<% end %>

Other People's Public Goals<BR>
<% @others_public_goals.each do |goal| %>
  <%= link_to goal.title, goal_url(goal.id) %>
  <br>
<% end %>
<BR>
<%= button_to "Add Goal", new_goal_url, method: :get %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<form action="<%=goals_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Title
    <input type="text" name="goal[title]" value="">
  </label>
  <BR>
  <label>
    Description<BR>
    <textarea name="goal[description]" rows="8" cols="40"></textarea>
  </label>
  <BR>
  <label>
    Visibility<BR>
    <label>
      Private
      <input type="radio" name="goal[visibility]" value="Private" checked>
    </label>
    <label>
      Public
      <input type="radio" name="goal[visibility]" value="Public">
    </label>
  </label>
  <BR>
  <label>
    Due Date
    <input type="date" name="goal[due_date]">
  </label>
  <BR>
  <label>
    Status
    <select name="goal[status]">
      <option value="not_started" selected>Not Started</option>
      <option value="in_progress">In Progress</option>
      <option value="completed">Completed</option>
    </select>
  </label>
  <BR>
  <input type="submit" value="Create New Goal">
</form>

app/views/goals/show.html.erb
<H1>Goal Show Page</H1>

<ul>
<% @goal.attributes.each do |k, v| %>
  <%= "<li>#{h(k.capitalize)} : #{h(v)}</li>".html_safe if v %>
<% end %>
</ul>

<% if current_user.id == @goal.user_id %>
  <%= button_to "Edit Goal", edit_goal_url(@goal), method: :get %><BR>
  <%= button_to "Delete Goal", goal_url(@goal), method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if signed_in? %>
  Hello, <%= current_user.username %>!
  <%= button_to "Sign Out", session_url, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_session_url %>
  <%= link_to "Sign Up", new_user_url %>
<% end %>

<%= flash[:errors].join("<BR>").html_safe if flash[:errors] %>
<%= flash[:notice].join("<BR>").html_safe if flash[:notice] %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<H1>Sign Up!</H1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Username
    <input type="text" name="user[username]">
  </label>
  <label>
    Password
    <input type="password" name="user[password]">
  </label>
  <input type="submit" value="Sign Up">
</form>